


-- 1 Board
-- Board 게시판
CREATE TABLE EDUBOARD(
	SEQ NUMBER,
	ID VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(500) NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	CREATEAT DATE
);

SELECT MAX(seq)
	FROM EDUBOARD e ;


-- 게시글 등록
INSERT INTO EDUBOARD (SEQ, ID, TITLE, CONTENT, DELFLAG, CREATEAT) 
			VALUES ( (SELECT NVL(MAX(SEQ), 0)+1 FROM EDUBOARD e) , 'user', '페이징TEST' || (SELECT MAX(seq)
				FROM EDUBOARD e ), '내용내용내용', 'N', SYSDATE);


INSERT INTO EDUBOARD (SEQ, ID, TITLE, CONTENT, DELFLAG, CREATEAT) 
			VALUES ( (SELECT NVL(MAX(SEQ), 0)+1 FROM EDUBOARD e) , 'user', '333333333333세번째 글 제목', '세번째 글의 내용', 'N', SYSDATE);
	
		
SELECT ROW_NUMBER() OVER(ORDER BY SEQ DESC) RN , SEQ ,ID ,TITLE, CONTENT , DELFLAG , CREATEAT 
	FROM EDUBOARD e ;
		


SELECT SEQ, ID, TITLE, CONTENT, DELFLAG, TO_CHAR(CREATEAT, 'yyyy-MM-dd') CREATEAT , NAME
	FROM (SELECT ROW_NUMBER() OVER(ORDER BY SEQ DESC) RN , SEQ ,ID ,TITLE, CONTENT , DELFLAG , CREATEAT , NAME
			FROM EDUBOARD e JOIN EMPINFO USING(ID) WHERE DELFLAG = 'N') 
	WHERE RN BETWEEN 1 AND 5;


		
-- 전체 게시글 개수
SELECT COUNT(*)
	FROM EDUBOARD ;
		
		
-- 게시글 전체 조회
SELECT SEQ, ID, TITLE, CONTENT, DELFLAG , CREATEAT , NAME
	FROM EDUBOARD e JOIN EMPINFO 
	USING (ID)
	WHERE DELFLAG = 'N';


-- 게시글 상세 조회
SELECT SEQ, ID, TITLE, CONTENT , DELFLAG , CREATEAT , NAME
	FROM EDUBOARD e JOIN EMPINFO
	USING (ID)
	WHERE SEQ = '1';


-- 게시글 삭제(다중삭제)
UPDATE EDUBOARD SET DELFLAG = 'Y' WHERE SEQ IN ( '1', '2');

-- 게시글 수정
UPDATE EDUBOARD SET CONTENT = '첫번째 게시글 내용 수정함' WHERE SEQ = '1';
 				
		
SELECT NVL(MAX(SEQ), 0)+1
	FROM EDUBOARD e ;





--- 2. 유저
CREATE TABLE EMPINFO 
		AS SELECT ID, PASSWORD, NAME, PHONE, ENABLE, AUTH 
			FROM MEMBERINFO m ;
	
ALTER TABLE EDUBOARD ADD CONSTRAINT EDUBOARD_PK PRIMARY KEY (SEQ);

ALTER TABLE EMPINFO ADD CONSTRAINT EMPINFO_PK PRIMARY KEY (ID);

ALTER TABLE EDUBOARD ADD CONSTRAINT EDUBOARD_FK FOREIGN KEY (ID) REFERENCES EMPINFO (ID);



-- 회원가입 신청 승인대기 enabel = D
INSERT INTO EMPINFO (ID, PASSWORD, NAME, PHONE, ENABLE, AUTH, PHOTO_STOREDNAME)
	VALUES ('newuser001', 'newuser001', '뉴유저', '01045678964' , 'D', 'USER' , '');



-- 로그인
SELECT ID ,PASSWORD ,NAME ,PHONE ,ENABLE ,AUTH 
	FROM EMPINFO e 
	WHERE  ID = 'user'
	AND PASSWORD = 'user'
	AND ENABLE = 'N';






--2024/06/20

-- 내가 쓴 글 조회
SELECT ROW_NUMBER () OVER(ORDER BY SEQ DESC) RN, 
	SEQ, ID, TITLE, CONTENT ,DELFLAG , TO_CHAR(CREATEAT, 'yyyy-MM-dd') CREATEAT  
	FROM EDUBOARD JOIN EMPINFO 
	USING(ID)
	WHERE ID = 'user'
	AND DELFLAG = 'N';


--내글 조회 5개씩
SELECT SEQ, ID, TITLE, CONTENT, DELFLAG, TO_CHAR(CREATEAT, 'yyyy-MM-dd') CREATEAT 
		FROM (SELECT ROW_NUMBER () OVER(ORDER BY SEQ DESC) RN, 
				SEQ, ID, TITLE, CONTENT ,DELFLAG , CREATEAT 
				FROM EDUBOARD JOIN EMPINFO 
				USING(ID)
				WHERE ID = 'user'
				AND DELFLAG = 'N')
	WHERE RN BETWEEN  1 AND 5;


--내글 개수
SELECT COUNT(*)
	FROM EDUBOARD 
	WHERE ID = 'user'
	AND DELFLAG = 'N';






SELECT SEQ, ID, TITLE, CONTENT, DELFLAG, TO_CHAR(CREATEAT, 'yyyy-MM-dd') CREATEAT , NAME
FROM (SELECT ROW_NUMBER() OVER(ORDER BY SEQ DESC) RN , SEQ ,ID ,TITLE, CONTENT , DELFLAG , CREATEAT , NAME
			FROM EDUBOARD e JOIN EMPINFO USING(ID) WHERE DELFLAG = 'N') 
WHERE RN BETWEEN 1 AND 5;





-- 아이디중복체크
SELECT ID
	FROM EMPINFO e 
	WHERE ID = 'HAPPY';

	
	

--3 관리자기능
	

-- 회원 목록 조회
SELECT ID, NAME ,PHONE , ENABLE , PHOTO_STOREDNAME 
	FROM EMPINFO e 
	WHERE AUTH = 'USER'
	ORDER BY ENABLE ;


SELECT ROW_NUMBER() OVER(ORDER BY ENABLE) RN
	,ID, NAME ,PHONE , ENABLE , PHOTO_STOREDNAME 
	FROM EMPINFO e 
	WHERE AUTH = 'USER'
	




-- 회원 상세 조회
SELECT ID, NAME ,PHONE , ENABLE , PHOTO_STOREDNAME
		FROM EMPINFO e 
		WHERE AUTH = 'USER'
		AND ID = 'user'
		ORDER BY ENABLE


-- 회원삭제
UPDATE EMPINFO SET ENABLE = 'N' WHERE ID = 'newUser';

--회원가입 승인
UPDATE EMPINFO SET ENABLE = 'Y' WHERE ID = 'newUser';

--회원가입 승인 거부
UPDATE EMPINFO SET ENABLE = 'F' WHERE ID = 'newUser';





-- 사진 업로드, 조회
ALTER TABLE EMPINFO ADD PHOTO_STOREDNAME VARCHAR2(500);













